version: 1.0.{build}

image:
- Visual Studio 2017

install:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: cl 04_variables_constant.c
  
build: false

test_script:
