version: 1.1.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/

image:
- Visual Studio 2017

install:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
# - ps: gci *.c | % {cl $($_.Fullname)}
- cmd: cl 01_helloworld.c
- cmd: cl 02_printf_char_int_float.c
- cmd: cl 03_For.c
- cmd: cl 04_variables_constant.c 
- cmd: cl 05_if_else_statements.c
# - cmd: FOR /F %f in ('dir *.c /a-d /b /o:-d') do cl %f

build: false

test_script:
